### ISSUE TITLE
"yarn run script" fails 

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa-sc-examples#1]
I have problems to build wasm with yarn here, however it's working fine in the other repo (massa-sc-templates):

```
seb:~/scm/massa-sc-examples (main)$ yarn helloworld
yarn run v1.22.17
$ asc --transform json-as/transform assembly/helloworld.ts --target release --exportRuntime --textFile build/helloworld.wat --binaryFile build/helloworld.wasm
FAILURE /home/seb/scm/massa-sc-examples/node_modules/json-as/transform/lib/index.js:148
    const firstKind = node.elementExpressions[0]?.kind;
                                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.main (/home/seb/scm/massa-sc-examples/node_modules/assemblyscript/cli/asc.js:567:25)
    at /home/seb/scm/massa-sc-examples/node_modules/assemblyscript/bin/asc:19:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by damip** [comment]
@sebastien-forestier  have you tried running "yarn install" in the folder before building the helloworld ?

**Comment by sebastien-forestier** [comment]
yes I did

**Comment by qdrn** [comment]
Is it still relevant with the last version ? @sebastien-forestier
